### ISSUE TITLE
HA don't like your addon ;)

### ISSUE THREAD

**Issue by lgLindstrom** [mdegat01/addon-loki#136]
Today I installed HA Operating system on a RPI4

As first addon I tried to install promtail. 
When adding this repository I got the following errror.
Am I doing something wrong wrong ??

```
22-01-01 18:09:12 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/mdegat01/addon-loki repository
22-01-01 18:09:13 ERROR (MainThread) [supervisor.store] https://github.com/mdegat01/addon-loki is not a valid add-on repository
22-01-01 18:09:13 INFO (MainThread) [supervisor.resolution.module] Create new issue IssueType.CORRUPT_REPOSITORY - ContextType.STORE / b6c46743
22-01-01 18:09:13 INFO (MainThread) [supervisor.resolution.module] Create new suggestion SuggestionType.EXECUTE_REMOVE - ContextType.STORE / b6c46743
22-01-01 18:09:14 WARNING (MainThread) [supervisor.store.data] No repository information exists at /data/addons/git/b6c46743
22-01-01 18:09:16 INFO (MainThread) [supervisor.store] Loading add-ons from store: 62 all - 0 new - 0 remove
22-01-01 18:09:16 INFO (MainThread) [supervisor.resolution.fixups.store_execute_remove] Remove invalid Store: b6c46743
```

**Comment by mdegat01** [comment]
Yes. This repo is not an addon repository. I follow the method frenck created for HA community addon's. Each addon is developed in its own repo and then updates are pushed to a different GitHub repo which serves as the addon repository.

In the addon panel add this as the addon repository

[https://github.com/mdegat01/hassio-addons](https://github.com/mdegat01/hassio-addons)

There's also a myhomeassistant button in the docs of each of my addons to easily add the addon repository in the "install" section.
